language: c
sudo: false
services:
  - docker
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-docker.sh
script: bash ./.travis-docker.sh
env:
  global:
    - PACKAGE=terminal_size
  matrix:
    - OCAML_VERSION=4.04 DISTRO=debian-stable
    - OCAML_VERSION=4.05 DISTRO=debian-stable
    - OCAML_VERSION=4.06 DISTRO=debian-stable
    - OCAML_VERSION=4.07 DISTRO=debian-stable
    - OCAML_VERSION=4.07 DISTRO=alpine
